name: Go
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18

    - name: install claat tool
      run: go install github.com/googlecodelabs/tools/claat@latest
      
    - name: Change to docs directory
      run: cd $GITHUB_WORKSPACE/docs
      
    # Generate html from all md files
    - name: Test
      run: claat export ../codelabs/*md -f offline
