# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages
on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: install claat tool
        run: go install github.com/googlecodelabs/tools/claat@latest
          
      - name: Change to docs directory
        run: cd $GITHUB_WORKSPACE/docs
          
        # Generate html from all md files
      - name: Export markdown to html
        run: claat export ../codelabs/*md -f offline
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@main
