name: Deploy static content to Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: install claat tool
        run: go install github.com/googlecodelabs/tools/claat@latest
      - name: Change to docs directory
        run: |
          mkdir $GITHUB_WORKSPACE/docs
          cd $GITHUB_WORKSPACE/docs
      - name: Export markdown to html
        run: claat export ../codelabs/*md
